name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'

      - name: Build binary
        run: go build -o wges

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: release-${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: "Automated release from main branch"
          draft: false
          prerelease: false

      - name: Upload binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./wges
          asset_name: wges-${{ github.run_number }}-linux-amd64
          asset_content_type: application/octet-stream
