name: Build and Release (Linux Only)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release Linux Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'

      - name: Build Binary
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/wges
          ls -lh dist/
          file dist/wges

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}
          files: dist/wges
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
