name: Build and Release (Linux Only)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release Linux Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'

      - name: Build Binary for Linux
        run: GOOS=linux GOARCH=amd64 go build -o wges

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Binary
        uses: softprops/action-gh-release@v1
        with:
          files: ./wges
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
